#!/bin/bash

python -c 'import sys; print(sys.real_prefix)' 2>/dev/null && INVENV=1 || INVENV=0

if [ $INVENV == 0 ]; then
    # Only activate the virtualenv if we aren't in one already
    source /usr/share/virtualenvwrapper/virtualenvwrapper.sh
    workon pocketstats
fi

if [ ! -f pocketstats.db ]; then
    python pocketstats.py createdb
fi

python pocketstats.py updatestats
