#!/bin/bash

if [[ -z "$VIRTUAL_ENV" ]]; then
    # Only activate the virtualenv if we aren't in one already
    source /usr/share/virtualenvwrapper/virtualenvwrapper.sh
    workon pocketstats
fi

if [ ! -f pocketstats.db ]; then
    python pocketstats.py createdb
fi

python pocketstats.py updatestats
